const { createClient } = window.supabase;
const SUPABASE_URL='https://vihbsfrwnslnmheowkhy.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_RNvbXKwTRLQU5WIYmX0A-g_zokdaYLe';
const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const SITE_URL=window.location.origin+window.location.pathname;
const authScreen=document.getElementById('authScreen'),appShell=document.getElementById('appShell'),authForm=document.getElementById('authForm'),authEmail=document.getElementById('authEmail'),authPassword=document.getElementById('authPassword'),authConfirmPassword=document.getElementById('authConfirmPassword'),confirmPasswordGroup=document.getElementById('confirmPasswordGroup'),togglePassword=document.getElementById('togglePassword'),toggleConfirmPassword=document.getElementById('toggleConfirmPassword'),passwordStrengthBar=document.getElementById('passwordStrengthBar'),passwordStrengthText=document.getElementById('passwordStrengthText'),authSubmit=document.getElementById('authSubmit'),authToggle=document.getElementById('authToggle'),forgotPassword=document.getElementById('forgotPassword'),authTitle=document.getElementById('authTitle'),authSubtitle=document.getElementById('authSubtitle'),authMessage=document.getElementById('authMessage'),signOut=document.getElementById('signOut'),userEmail=document.getElementById('userEmail');
let signUpMode=false;
function showMessage(text,error=false){authMessage.textContent=text;authMessage.className=`auth-message ${error?'error':''}`}
function renderAuth(){authScreen.classList.remove('hidden');appShell.classList.add('hidden')}
function renderApp(user){authScreen.classList.add('hidden');appShell.classList.remove('hidden');userEmail.textContent=user?.email||''}
async function checkSession(){const{data,error}=await supabase.auth.getSession();if(error)showMessage(error.message,true);if(data.session?.user)renderApp(data.session.user);else renderAuth()}
supabase.auth.onAuthStateChange((_event,session)=>session?.user?renderApp(session.user):renderAuth());
function setupVisibilityToggle(input,button){if(!input||!button)return;button.addEventListener('click',()=>{const visible=input.type==='text';input.type=visible?'password':'text';button.textContent=visible?'👁':'🙈'})}
setupVisibilityToggle(authPassword,togglePassword);setupVisibilityToggle(authConfirmPassword,toggleConfirmPassword);
function updatePasswordStrength(){if(!passwordStrengthBar||!passwordStrengthText)return;const p=authPassword.value;let s=0;if(p.length>=8)s++;if(/[a-z]/.test(p))s++;if(/[A-Z]/.test(p))s++;if(/\d/.test(p))s++;if(/[^A-Za-z0-9]/.test(p))s++;passwordStrengthBar.style.width=`${s*20}%`;passwordStrengthText.textContent=s===0?'Use 8+ characters with uppercase, lowercase, number and symbol.':s<3?'Weak password — add more character types.':s<5?'Good password — add more variety.':'Strong password ✓'}
authPassword.addEventListener('input',updatePasswordStrength);
function setAuthMode(create){signUpMode=create;authTitle.textContent=create?'Create your account':'Welcome back';authSubtitle.textContent=create?'Join Veylola AI and start your private workspace':'Sign in to your private AI workspace';authSubmit.innerHTML=create?'<span>Create account</span><b>→</b>':'<span>Sign in</span><b>→</b>';authToggle.innerHTML=create?'Already have an account? <span>Sign in →</span>':'Create your Veylola account <span>→</span>';confirmPasswordGroup.style.display=create?'block':'none';confirmPasswordGroup.classList.toggle('hidden-field',!create);forgotPassword.style.display=create?'none':'block';authConfirmPassword.required=create;authPassword.minLength=create?8:6;if(!create)authConfirmPassword.value='';updatePasswordStrength();showMessage('')}
authToggle.onclick=()=>setAuthMode(!signUpMode);confirmPasswordGroup.style.display='none';
authForm.addEventListener('submit',async e=>{e.preventDefault();const email=authEmail.value.trim(),password=authPassword.value,confirm=authConfirmPassword.value;if(!email||!password)return showMessage('Enter your email and password.',true);if(signUpMode){if(password.length<8)return showMessage('Password must be at least 8 characters.',true);if(!/[a-z]/.test(password)||!/[A-Z]/.test(password)||!/\d/.test(password))return showMessage('Use uppercase, lowercase and at least one number.',true);if(password!==confirm)return showMessage('Passwords do not match.',true)}authSubmit.disabled=true;showMessage(signUpMode?'Creating your account...':'Signing you in...');try{if(signUpMode){const{data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:SITE_URL}});if(error)throw error;if(data.session&&data.user)renderApp(data.user);else{showMessage('Account created. Check your email to confirm it.');setAuthMode(false);authEmail.value=email;authPassword.value=''}}else{const{data,error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;if(data.user)renderApp(data.user)}}catch(error){showMessage(error.message||'Authentication failed.',true)}finally{authSubmit.disabled=false}});
forgotPassword.addEventListener('click',async()=>{const email=authEmail.value.trim();if(!email)return showMessage('Enter your email address first.',true);try{const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:SITE_URL});if(error)throw error;showMessage('Password reset email sent.')}catch(error){showMessage(error.message||'Could not send reset email.',true)}});
signOut.addEventListener('click',async()=>{const{error}=await supabase.auth.signOut();if(error)showMessage(error.message,true)});
const messages=document.getElementById('messages'),form=document.getElementById('chatForm'),input=document.getElementById('prompt'),send=document.getElementById('send');let history=[];
function isBuildRequest(text){return /\b(build|create|make|develop|design|generate)\b/i.test(text)&&/\b(app|application|website|web app|mobile|android|ios|game|platform|software|site|project|tool|dashboard|chatbot)\b/i.test(text)}
function addMessage(role,text){const welcome=messages.querySelector('.welcome');if(welcome)welcome.remove();const el=document.createElement('div');el.className=`message ${role}`;el.innerHTML=`<div class="avatar">${role==='user'?'You':'✦'}</div><div class="message-content"></div>`;el.querySelector('.message-content').textContent=text;messages.appendChild(el);messages.scrollTop=messages.scrollHeight;return el.querySelector('.message-content')}
function addBuildCard(container,prompt){const card=document.createElement('div');card.className='build-card';card.innerHTML=`<div class="build-head"><div class="build-icon">✦</div><div><strong>Veylola Build</strong><small>Turning your idea into a project</small></div></div><div class="build-progress"><div class="build-step active"><i></i> Understanding your idea</div><div class="build-step"><i></i> Planning screens and features</div><div class="build-step"><i></i> Generating the project</div><div class="build-step"><i></i> Preparing a runnable build</div></div><button class="build-button" type="button">Open build workspace</button>`;container.appendChild(card);return card}
async function ask(text){const build=isBuildRequest(text);addMessage('user',text);history.push({role:'user',content:text});send.disabled=true;const out=addMessage('assistant',build?'I’ll turn that into a build plan first.':'Thinking...');if(build){addBuildCard(out,'');out.textContent='';const card=out.querySelector('.build-card');if(!card)addBuildCard(out,text)}try{const messagesForAI=build?[{role:'user',content:`You are Veylola Build AI. The user wants you to build something like a Rork-style AI app builder. Analyze this request and provide a concise build specification with: app type, core features, screens, visual style, data/backend needs, and the first implementation steps. Do not claim that an APK has already been generated. User request: ${text}`}]:history;const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:messagesForAI})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed');if(build){const card=out.querySelector('.build-card');const note=document.createElement('div');note.style.cssText='margin-top:12px;color:#aeb7c5;font-size:12px;line-height:1.55;white-space:pre-wrap';note.textContent=data.reply;out.appendChild(note);history.push({role:'assistant',content:data.reply})}else{out.textContent=data.reply;history.push({role:'assistant',content:data.reply})}}catch(e){out.textContent='Veylola AI could not connect right now. Check your API deployment and key.'}finally{send.disabled=false;input.focus()}}
form.addEventListener('submit',e=>{e.preventDefault();const text=input.value.trim();if(!text)return;input.value='';input.style.height='auto';ask(text)});
input.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,150)+'px'});
document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{input.value=b.dataset.prompt;form.requestSubmit()});
const resetChat=()=>{history=[];messages.innerHTML='<div class="welcome"><div class="hero-logo">✦</div><h1>What will you build?</h1><p>Ask Veylola anything — or describe an app you want to create.</p><div class="quick-prompts"><button type="button" data-prompt="Build me a modern mobile shopping app">Build a shopping app</button><button type="button" data-prompt="Build a social media app with profiles and chat">Build a social app</button><button type="button" data-prompt="Build a portfolio website for a creative agency">Build a website</button></div></div>';messages.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{input.value=b.dataset.prompt;form.requestSubmit()});input.focus()};
document.getElementById('newChat').onclick=resetChat;document.getElementById('newChatMobile').onclick=resetChat;
document.getElementById('menuButton').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
document.getElementById('micButton').onclick=()=>{if(!('webkitSpeechRecognition'in window||'SpeechRecognition'in window)){input.placeholder='Voice input is not supported here';return}const R=window.SpeechRecognition||window.webkitSpeechRecognition;const rec=new R();rec.lang='en-NG';rec.onresult=e=>{input.value=e.results[0][0].transcript;input.dispatchEvent(new Event('input'))};rec.start()};
checkSession();
